name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci --force

      - name: Build
        run: npm run build --if-present
        env:
          NEXT_PUBLIC_HANKO_API_URL: test

      - name: Run Linter
        run: npm run lint